### ISSUE TITLE
support comparison ops and returning bools

### ISSUE THREAD

**Issue by brentp** [Yardanico/nim-mathexpr#1]
great library!

any chance of supporting e.g. : `eval("a > 22", {"a": 5.0})`? 
I can use, e.g.:

```nim
proc gt(args: seq[float]): float =
  if args[0] <= args[1]: return 0.0
  return 1

mathexpr.functions["gt"] = gt
echo eval("gt(a, 4)", {"a": 5.0})
```

but it would be nice to have support for this. I see that everything is `float` as it is now, but thought you might have some ideas on this.
thanks.

**Comment by daef** [comment]
i'd use `sgn(a-4)`: it's -1 if a<4, 0 if a==4 and 1 if a>4
