### ISSUE TITLE
all functions with expected len -1 are broken

### ISSUE THREAD

**Issue by daef** [Yardanico/nim-mathexpr#2]
functions like 'min' that checkArgs(-1) are broken because they evaluate true [here](https://github.com/Yardanico/nim-mathexpr/blob/master/src/mathexpr/expr_eval.nim#L65).

I help myself by patching the existing functions like

    e.addFunc("min", proc (a:seq[float]): float = a.min)

but I guess it would be nice (and easy) to fix CheckArgLen.

**Comment by Yardanico** [comment]
Fixed, probably it could be done the easier way, but maybe I'll try that later :)

**Comment by Yardanico** [comment]
And yeah, I should probably add tests for all math functions

**Comment by daef** [comment]
you could also add s(i)gn (at least that's one i was missing)

**Comment by Yardanico** [comment]
> you could also add s(i)gn (at least that's one i was missing)

You mean https://en.wikipedia.org/wiki/Sign_function ?

**Comment by daef** [comment]
yes, but no worries, it's already in [math.nim](https://nim-lang.org/docs/math.html#sgn%2CT)
