### ISSUE TITLE
Simple sum gives wrong result

### ISSUE THREAD

**Issue by jerous86** [Yardanico/nim-mathexpr#4]
```
import mathexpr
let e = newEvaluator()
echo e.eval("0.0767999999999999+0")
echo e.eval("0.076799999999999+0")
```
gives me as output
```
767999999999999.0
0.076799999999999
```

The first line is obviously incorrect.

**Comment by Yardanico** [comment]
Ah nevermind I see that you reported this issue yourself https://github.com/nim-lang/Nim/issues/18702 :)

**Comment by jerous86** [comment]
Ah yes, sorry, I forgot to refer to the issue here :)
Yes, it can be closed, I didn't encounter any other problems.
